import { StyleSheet } from 'react-native';

import { colors } from '@/constants/shinecraft-theme';

export const vehicleStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  content: { padding: 20, paddingBottom: 36, gap: 16 },
  header: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  headerText: { flex: 1 },
  title: { color: colors.ink, fontSize: 30, fontWeight: '900' },
  subtitle: { color: colors.muted, marginTop: 5, lineHeight: 19 },
  addButton: { paddingHorizontal: 15, paddingVertical: 11, borderRadius: 12, backgroundColor: colors.primary },
  addButtonText: { color: '#fff', fontWeight: '800' },
  statsRow: { gap: 10 },
  summaryCard: { padding: 18, borderRadius: 18, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
  summaryLabel: { color: colors.muted, fontSize: 12, fontWeight: '700' },
  summaryValue: { color: colors.ink, fontSize: 24, fontWeight: '900', marginTop: 5 },
  loader: { paddingVertical: 50 },
  empty: { padding: 28, borderRadius: 18, alignItems: 'center', backgroundColor: colors.surface, gap: 8 },
  emptyTitle: { color: colors.ink, fontSize: 18, fontWeight: '800' },
  emptyText: { color: colors.muted, textAlign: 'center', lineHeight: 20 },
  emptyButton: { marginTop: 8, paddingHorizontal: 18, paddingVertical: 11, borderRadius: 12, backgroundColor: colors.primary },
  emptyButtonText: { color: '#fff', fontWeight: '800' },
  card: { padding: 18, borderRadius: 19, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, gap: 13 },
  cardHeader: { flexDirection: 'row', alignItems: 'center', gap: 13 },
  vehicleMark: { width: 54, height: 48, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.tint },
  vehicleMarkText: { color: colors.primary, fontSize: 13, fontWeight: '900' },
  vehicleInfo: { flex: 1 },
  vehicleName: { color: colors.ink, fontSize: 18, fontWeight: '800' },
  vehicleMeta: { color: colors.primary, marginTop: 4, fontWeight: '800' },
  vehicleSubMeta: { color: colors.muted, marginTop: 4 },
  actions: { flexDirection: 'row', gap: 10 },
  secondaryButton: { flex: 1, alignItems: 'center', padding: 11, borderRadius: 11, backgroundColor: colors.tint },
  secondaryButtonText: { color: colors.primary, fontWeight: '800' },
  deleteButton: { paddingHorizontal: 20, alignItems: 'center', justifyContent: 'center', borderRadius: 11, backgroundColor: '#fef3f2' },
  deleteText: { color: colors.danger, fontWeight: '800' },
  requestSection: { padding: 18, borderRadius: 19, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, gap: 12 },
  sectionTitle: { color: colors.ink, fontSize: 19, fontWeight: '900' },
  sectionSubtitle: { color: colors.muted, marginTop: -4 },
  requestList: { gap: 10 },
  requestCard: { padding: 14, borderRadius: 14, backgroundColor: colors.background, gap: 6 },
  requestTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 },
  requestPlate: { color: colors.ink, fontWeight: '900' },
  requestRelationship: { color: colors.muted, fontWeight: '700' },
  requestNote: { color: colors.ink, lineHeight: 19 },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 999 },
  statusText: { fontSize: 11, fontWeight: '800' },
  modalSafe: { flex: 1, backgroundColor: colors.background },
  modalContent: { padding: 20, paddingBottom: 40, gap: 16 },
  modalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 5 },
  modalTitle: { color: colors.ink, fontSize: 26, fontWeight: '900', flex: 1, paddingRight: 12 },
  close: { color: colors.primary, fontWeight: '800' },
  formPanel: {
    padding: 16,
    borderRadius: 16,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 12,
  },
  panelTitle: { color: colors.ink, fontSize: 18, fontWeight: '900' },
  panelCaption: { color: colors.muted, lineHeight: 19 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  helperText: { color: colors.muted, lineHeight: 19, backgroundColor: colors.surface, padding: 12, borderRadius: 12 },
  saveButton: { minHeight: 52, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primary },
  saveText: { color: '#fff', fontSize: 16, fontWeight: '800' },
  selectFieldWrap: { gap: 7 },
  selectFieldLabel: { color: colors.ink, fontSize: 14, fontWeight: '700' },
  selectFieldButton: {
    minHeight: 52,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    backgroundColor: colors.surface,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  selectFieldButtonDisabled: { backgroundColor: '#f2f4f7', borderColor: '#eaecf0' },
  selectFieldValue: { flex: 1, color: colors.ink, fontSize: 16 },
  selectFieldPlaceholder: { color: '#98a2b3' },
  selectFieldValueDisabled: { color: '#98a2b3' },
  selectFieldChevron: { color: colors.muted, fontSize: 18, marginTop: -4 },
  imagePickerButton: {
    minHeight: 52,
    borderWidth: 1,
    borderColor: colors.primary,
    borderStyle: 'dashed',
    borderRadius: 14,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.tint,
  },
  imagePickerButtonText: { color: colors.primary, fontSize: 15, fontWeight: '800' },
  imagePickerButtonMeta: { color: colors.muted, fontSize: 13, fontWeight: '700' },
  imageSection: { gap: 8 },
  imageSectionTitle: { color: colors.ink, fontSize: 13, fontWeight: '700' },
  imageRow: { gap: 10, paddingRight: 4 },
  previewCard: { position: 'relative' },
  previewImage: { width: 96, height: 96, borderRadius: 14, backgroundColor: colors.background },
  removeImageButton: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(16, 24, 40, 0.78)',
  },
  removeImageButtonText: { color: '#fff', fontSize: 16, fontWeight: '900', lineHeight: 18 },
  sheetBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(16, 24, 40, 0.4)' },
  sheetOverlay: { flex: 1 },
  sheetCard: {
    maxHeight: '78%',
    backgroundColor: colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 14,
    paddingHorizontal: 18,
    paddingBottom: 20,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  sheetTitle: { color: colors.ink, fontSize: 20, fontWeight: '900', flex: 1, paddingRight: 12 },
  sheetClose: { color: colors.primary, fontWeight: '800' },
  sheetBody: { marginTop: 12 },
  sheetBodyContent: { paddingBottom: 12, gap: 16 },
  sheetSection: { gap: 8 },
  sheetSectionTitle: { color: colors.muted, fontSize: 12, fontWeight: '800', textTransform: 'uppercase' },
  sheetOption: {
    minHeight: 48,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  sheetOptionActive: { borderColor: colors.primary, backgroundColor: colors.tint },
  sheetOptionText: { flex: 1, color: colors.ink, fontSize: 15, fontWeight: '600' },
  sheetOptionTextActive: { color: colors.primary, fontWeight: '800' },
  sheetOptionCheck: { color: colors.primary, fontSize: 16, fontWeight: '900' },
  sheetEmpty: { paddingVertical: 24, alignItems: 'center' },
  sheetEmptyText: { color: colors.muted, textAlign: 'center', lineHeight: 20 },
  detailBlock: { padding: 16, borderRadius: 16, backgroundColor: colors.surface, gap: 12 },
  detailRow: { gap: 4 },
  detailLabel: { color: colors.muted, fontSize: 12, fontWeight: '700' },
  detailValue: { color: colors.ink, fontSize: 15, fontWeight: '800' },
  gallery: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  galleryImage: { width: '48%', aspectRatio: 1, borderRadius: 14, backgroundColor: colors.surface },
  emptyGallery: { padding: 20, borderRadius: 16, backgroundColor: colors.surface, alignItems: 'center' },
  emptyGalleryText: { color: colors.muted, textAlign: 'center' },
  dialogBackdrop: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 20, backgroundColor: 'rgba(16, 24, 40, 0.55)' },
  dialogCard: { width: '100%', maxWidth: 520, padding: 20, borderRadius: 20, backgroundColor: colors.surface, gap: 12 },
  dialogTitle: { color: colors.ink, fontSize: 22, fontWeight: '900' },
  dialogText: { color: colors.muted, lineHeight: 20 },
  noteInput: { minHeight: 100, textAlignVertical: 'top', paddingTop: 14 },
  dialogActions: { flexDirection: 'row', gap: 10, marginTop: 4 },
  keepButton: { flex: 1, minHeight: 48, alignItems: 'center', justifyContent: 'center', borderRadius: 13, borderWidth: 1, borderColor: colors.border },
  keepButtonText: { color: colors.ink, fontWeight: '800' },
  confirmButton: { flex: 1, minHeight: 48, alignItems: 'center', justifyContent: 'center', borderRadius: 13, backgroundColor: colors.primary },
  confirmButtonText: { color: '#fff', fontWeight: '800' },
  buttonDisabled: { opacity: 0.5 },
});
